{{- if eq .Values.cassandraLocation "off-cluster" }}   
kind: Service
apiVersion: v1
metadata:
  name: cassandra
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.cassandra.host0 }}
{{- end }}
