apiVersion: v1
kind: Service
metadata:
  annotations:
    apigw.version: 1.7.0 (767ab4b)
  creationTimestamp: null
  labels:
    io.apigw.service: mysql
  name: mysql
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    io.apigw.service: mysql
  sessionAffinity: ClientIP
  type: ClusterIP
