{{- if eq .Values.nodeport.enabled true }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.anm.name }}
  name: {{ .Values.anm.name }}-ext
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.anm.name }}
  ports:
  - port: {{ .Values.anm.trafficPort }}
    protocol: TCP
    nodePort: {{ .Values.anm.nodePort }}
{{- end }}