apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.anm.name }}
  name: {{ .Values.anm.name }}-int
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.anm.name }}
  ports:
  - name: ui
    port: {{ .Values.anm.trafficPort }}
    targetPort: {{ .Values.anm.trafficPort }}
    protocol: TCP
  sessionAffinity: ClientIP
  type: ClusterIP

