{{- if eq .Values.nodeport.enabled false }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.anm.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
    - {{ .Values.anm.name }}.{{ .Values.namespace }}.{{ .Values.ingress.host }}.nip.io
  rules:
  - host: {{ .Values.anm.name }}.{{ .Values.namespace }}.{{ .Values.ingress.host }}.nip.io
    http:
      paths:
      - backend:
          serviceName: {{ .Values.anm.name }}-int
          servicePort: 8090
{{- end }}
