{{- if and (eq .Values.apimgr.enabled true) (eq .Values.nodeport.enabled true) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.apimgr.name }}
  name: {{ .Values.apimgr.name }}-ext
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.apimgr.name }}
  ports:
  - name: http{{ .Values.apimgr.trafficPort }}
    port: {{ .Values.apimgr.trafficPort }}
    protocol: TCP
    nodePort: {{ .Values.apimgr.nodePort }}
  - name: http{{ .Values.apimgr.openPort }}
    port: {{ .Values.apimgr.openPort }}
    protocol: TCP
    nodePort: {{ .Values.apimgr.nodePortOpen }}
{{- end }}
